@echo off
color 0a
title OSCC App - Automated Start Sequence

echo =======================================================
echo          OSCC AI App Automator
echo =======================================================
echo.

:: -------------------------------------------------------------
:: 1. Check for Administrator Privileges (needed for Firewall)
:: -------------------------------------------------------------
net session >nul 2>&1
if %errorLevel% neq 0 (
    echo [!] Administrator privileges required.
    echo Please wait, requesting admin rights...
    
    :: Creates a temporary VBS script to elevate privileges automatically
    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    echo UAC.ShellExecute "cmd.exe", "/c ""%~s0""", "", "runas", 1 >> "%temp%\getadmin.vbs"
    
    "%temp%\getadmin.vbs"
    del "%temp%\getadmin.vbs"
    
    :: Exit this window because a new Admin window is opening
    exit /B
)

:: Changing to the correct directory after becoming admin
cd /D "%~dp0"

:: -------------------------------------------------------------
:: 2. Configure Windows Firewall automatically
:: -------------------------------------------------------------
echo [1/4] Checking Firewall for Port 5000 (Flask) and 8081 (Expo)...

:: Flask Firewall Rule
netsh advfirewall firewall show rule name="OSCC Flask" >nul
if not ERRORLEVEL 1 (
    echo   - Flask Firewall rule exists. ✅
) else (
    netsh advfirewall firewall add rule name="OSCC Flask" dir=in action=allow protocol=TCP localport=5000 >nul
    echo   - Flask Firewall rule created! ✅
)

:: Expo Firewall Rule
netsh advfirewall firewall show rule name="OSCC Expo" >nul
if not ERRORLEVEL 1 (
    echo   - Expo Firewall rule exists. ✅
) else (
    netsh advfirewall firewall add rule name="OSCC Expo" dir=in action=allow protocol=TCP localport=8081 >nul
    echo   - Expo Firewall rule created! ✅
)
echo.

:: -------------------------------------------------------------
:: 3. Detect the computer's active Wi-Fi IPv4 address
:: -------------------------------------------------------------
echo [2/4] Detecting Local Network IP Address...
setlocal EnableDelayedExpansion
set "IP_ADDRESS="

:: Parse ipconfig and ignore any addresses starting with 169.254 (APIPA/Virtual)
for /f "tokens=2 delims=:" %%A in ('ipconfig ^| findstr /C:"IPv4 Address"') do (
    set "temp_ip=%%A"
    :: Strip any leading spaces
    set "IP_ADDRESS=!temp_ip: =!"
    
    :: Check if it starts with 169.254. If it DOES NOT, we found our real IP!
    echo !IP_ADDRESS! | findstr /b "169.254" >nul
    if errorlevel 1 goto :foundIP
)

:foundIP
:: End delayed expansion, passing the variable outside the block
endlocal & set "IP_ADDRESS=%IP_ADDRESS%"

:: Failsafe if completely disconnected
if "%IP_ADDRESS%"=="" (
    echo [!] WARNING: Could not detect IP. Connecting to fallback.
    set IP_ADDRESS=127.0.0.1
) else (
    echo   - Found IP Address: %IP_ADDRESS% ✅
)
echo.

:: -------------------------------------------------------------
:: 4. Update the mobile app configuration file (config.js)
:: -------------------------------------------------------------
echo [3/4] Auto-updating config.js to use %IP_ADDRESS%...
powershell -NoProfile -Command "$content = \"// Auto-generated by start_oscc.bat`nimport { Platform } from 'react-native';`n`nexport const BACKEND_URL = Platform.OS === 'web'`n  ? 'http://localhost:5000'`n  : 'http://%IP_ADDRESS%:5000';`n\"; Set-Content -Path '.\mobile_app\config.js' -Value $content -Encoding UTF8"
echo   - Configuration updated! ✅
echo.

:: -------------------------------------------------------------
:: 5. Launch both servers in separate pop-up windows
:: -------------------------------------------------------------
echo [4/4] Starting Flask Backend and Expo Mobile App...
echo.

:: Launch Python Backend
echo   - Launching Backend Server...
start "OSCC Backend" cmd /k "color 0B && title OSCC Backend Server && cd /d .\backend && echo ========================== && echo FLASK BACKEND RUNNING && echo ========================== && py -3.12 app.py"

:: Give backend 3 seconds to spin up
timeout /t 3 /nobreak >nul

:: Launch Expo Frontend (Forcing the specific Wi-Fi IP to avoid Virtual Adapters)
echo   - Launching Frontend Expo Server...
start "OSCC Expo Mobile App" cmd /k "color 0d && title OSCC Expo && cd /d .\mobile_app && echo ========================== && echo EXPO RUNNING ON %IP_ADDRESS% && echo ========================== && npx expo start --host lan"

echo.
echo =======================================================
echo   🚀 COMPLETE! APP IS LAUNCHING 🚀
echo =======================================================
echo  1. Two new black windows have opened. Keep them open!
echo  2. Scan the QR code appearing in the purple/pink window.
echo  3. Your phone is now safely connected to %IP_ADDRESS%
echo =======================================================
echo.
pause
